
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.compi2.usac.analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int error = 1;
  public static final int minus = 4;
  public static final int number = 2;
  public static final int by = 5;
  public static final int divided = 6;
  public static final int EOF = 0;
  public static final int plus = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "number",
  "plus",
  "minus",
  "by",
  "divided"
  };
}

